name: Build static libs

on:
  workflow_dispatch:

concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

env:
  VCPKG_DISABLE_METRICS: 1

jobs:
  export-rocksdb:

    strategy:
      matrix:
        include:
          - os: macos-latest
            triplet: x64-osx
          - os: ubuntu-latest
            triplet: x64-linux
          - os: windows-latest
            triplet: x64-mingw-static
          - os: windows-latest
            triplet: x64-windows-static
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:

      #- name: install CMake
      #  uses: lukka/get-cmake@latest

      #- name: cache vcpkg
      #  uses: actions/cache@v3
      #  with:
      #    path: ~/vcpkg
      #    key: vcpkg-${{ runner.os }}

      - name: checkout vcpkg
        uses: actions/checkout@v3
        with:
          ref: 2023.01.09
          path: ~/vcpkg
          fetch-depth: 1

      - name: setup vcpkg
        uses: lukka/run-vcpkg@v10
        with:
          vcpkgDirectory: ~/vcpkg
          # vcpkgJsonGlob: '**/vcpkg.json'
          # runVcpkgInstall: true

      - name: package libs
        run: >-
          ./vcpkg export rocksdb
            zstd
            zlib
            snappy
            lz4
            bzip2 
            --triplet=${{ matrix.triplet }}

      - name: invalidate vcpkg cache
        run: echo "RUNVCPKG_NO_CACHE=1" >> $GITHUB_ENV
        if: ${{ failure() || cancelled() }}


      # TODO rename & upload packaged libs
