name: Build static libs

on:
  pull_request: # TODO remove, temp added for quicker testing
  workflow_dispatch:

concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

env:
  VCPKG_DISABLE_METRICS: 1

jobs:
  export-rocksdb:

    strategy:
      matrix:
        include:
          - os: macos-latest
            triplet: x64-osx
          - os: ubuntu-latest
            triplet: x64-linux
          - os: windows-latest
            triplet: x64-mingw-static
          - os: windows-latest
            triplet: x64-windows-static
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:

      - name: cache vcpkg
        uses: actions/cache@v3
        with:
          path: .
          key: vcpkg-${{ runner.os }}

      - name: checkout vcpkg
        uses: actions/checkout@v3
        with:
          repository: microsoft/vcpkg
          ref: 2023.01.09
          fetch-depth: 1

      - name: setup vcpkg
        run: ./bootstrap-vcpkg.sh

      - name: build & package libs
        run: |
          ./vcpkg export                                \ 
            rocksdb                                     \
            zstd                                        \
            zlib                                        \
            snappy                                      \
            lz4                                         \
            bzip2                                       \
            --zip                                       \
            --triplet=${{ matrix.triplet }}             \
            --output=rocksdb-${{ matrix.triplet }}      \
            --output-dir=$HOME

      - name: upload packaged libs
        if: success()
        uses: actions/upload-artifact@v3
        with:
#          name: build-report-${{ runner.os }}${{ github.action }}
          path: ~/rocksdb-${{ matrix.triplet }}.zip
          #if-no-files-found: ignore
