name: Build static libs

on:
  pull_request: # TODO remove, temp added for quicker testing
  workflow_dispatch:

concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

env:
  ROCKSDB_VERSION: 7.8.3

  VCPKG_DISABLE_METRICS: 1
  VCPKG_DEFAULT_BINARY_CACHE: /tmp/vcpkg-cache

jobs:
  export-rocksdb:

    strategy:
      matrix:
        include:
          - os: macos-latest
            triplet: x64-osx
            vcpkg-cmd: ./vcpkg
          - os: ubuntu-latest
            triplet: x64-linux
            vcpkg-cmd: ./vcpkg
          - os: windows-latest
            triplet: x64-mingw-static
            vcpkg-cmd: vcpkg
          - os: windows-latest
            triplet: x64-windows-static
            vcpkg-cmd: vcpkg
      fail-fast: false
    runs-on: ${{ matrix.os }}
    env:
      VCPKG_DEFAULT_TRIPLET: ${{ matrix.triplet }}
    steps:

      - name: cache vcpkg
        uses: actions/cache@v3
        with:
          path: |
            ${{ env.VCPKG_DEFAULT_BINARY_CACHE }}
          key: vcpkg-${{ runner.os }}

      - name: checkout vcpkg
        uses: actions/checkout@v3
        with:
          repository: microsoft/vcpkg
          ref: 2023.01.09
          fetch-depth: 1

      - name: prep
        shell: bash
        run: mkdir ${{ env.VCPKG_DEFAULT_BINARY_CACHE }}

      - name: setup vcpkg
        run: ./bootstrap-vcpkg.sh

      - name: create vcpkg.json
        shell: bash
        run: |
          touch vcpkg.json;
  
          cat <<EOT >> vcpkg.json
          {
            "dependencies": [
              "rocksdb",
              "zstd",
              "zlib",
              "snappy",
              "lz4",
              "bzip2"
            ],
            "overrides": [
              { "name": "rocksdb", "version": "${{ env.ROCKSDB_VERSION }}" }
            ]
          }
          EOT

      - name: update vcpkg.json
        shell: bash
        run: ${{ matrix.vcpkg-cmd }} x-update-baseline --add-initial-baseline

      - name: install libs
        shell: bash
        run: ${{ matrix.vcpkg-cmd }} install

      - name: list files
        shell: bash
        run: tree

      - name: upload packaged libs
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: rocksdb-${{ env.ROCKSDB_VERSION }}
          #if-no-files-found: ignore
          path: |
            ./installed/${{ matrix.triplet }}/lib/*.a
