name: Build static libs

on:
  pull_request: # TODO remove, temp added for quicker testing
  workflow_dispatch:

concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

env:
  VCPKG_DISABLE_METRICS: 1

jobs:
  export-rocksdb:

    strategy:
      matrix:
        rocksdb-version: [ 7.8.3 ]
        include:
          - os: macos-latest
            triplet: x64-osx
          - os: ubuntu-latest
            triplet: x64-linux
          - os: windows-latest
            triplet: x64-mingw-static
          - os: windows-latest
            triplet: x64-windows-static
      fail-fast: false
    runs-on: ${{ matrix.os }}
    env:
      VCPKG_DEFAULT_TRIPLET: ${{ matrix.triplet }}
    steps:

      - name: cache vcpkg
        uses: actions/cache@v3
        with:
          path: .
          key: vcpkg-${{ runner.os }}

      - name: checkout vcpkg
        uses: actions/checkout@v3
        with:
          repository: microsoft/vcpkg
          ref: 2023.01.09
          fetch-depth: 1

      - name: setup vcpkg
        run: ./bootstrap-vcpkg.sh

      - name: create vcpkg.json
        run: |
          touch vcpkg.json;
  
          cat <<EOT >> vcpkg.json
          {
            "dependencies": [
              "rocksdb",
              "zstd",
              "zlib",
              "snappy",
              "lz4",
              "bzip2"
            ],
            "overrides": [
              { "name": "rocksdb", "version": "${{ matrix.rocksdb-version }}" }
            ]
          }
          EOT

      - name: update vcpkg.json
        shell: bash
        run: ./vcpkg x-update-baseline --add-initial-baseline

      - name: install libs
        shell: bash
        run: ./vcpkg install

      - name: package libs
        shell: bash
        run: ./vcpkg export rocksdb zstd zlib snappy lz4 bzip2 --raw --output=rocksdb-${{ matrix.triplet }} --output-dir=$HOME/rdb-export

      - name: upload packaged libs
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: rocksdb-${{ matrix.rocksdb-version }}
          path: "~/rdb-export/**/installed/${{ matrix.triplet }}/lib/*.a"
          #if-no-files-found: ignore
