name: Build static libs

# Utility for building RocksDB static libraries for each platform

on:
  pull_request:
    paths:
      - ./.github/workflows/build_static_libs_2.yml
  workflow_dispatch:

concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true


permissions:
  contents: read


jobs:

  export-rocksdb:
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Cache Kotlin Konan
        id: cache-kotlin-konan
        uses: actions/cache@v3
        with:
          path: |
            ~/.konan/**/*
          key: kotlin-konan-${{ runner.os }}

      - uses: gradle/gradle-build-action@v2
        with:
          gradle-home-cache-cleanup: true
          arguments: >
            :externals:lib-rocksdb:rocksDbZip --info --stacktrace

      - name: upload packaged libs
        if: success()
        uses: actions/upload-artifact@v3
        with:
          path: |
            ./externals/lib-rocksdb/build/distributions/*.zip

      - name: Upload build reports
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: build-report-${{ runner.os }}${{ github.action }}
          path: "**/build/reports/"
          if-no-files-found: ignore
