name: Gradle Task
run-name: "Gradle Task ${{ inputs.gradle-task }} @ ${{ inputs.runs-on }}"

# Reusable Workflow for running a Gradle task

on:
  workflow_dispatch:

  workflow_call:
    inputs:
      gradle-task:
        description: "The Gradle task to run, including any flags"
        required: true
        type: string
      runs-on:
        description: "OSes to run the task on"
        required: true
        type: string


concurrency:
  # note: the Workflow inputs are also included in the concurrency group
  group: "${{ github.workflow }} ${{ join(inputs.*) }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true


permissions:
  contents: read


jobs:

  run-task:
    runs-on: ${{ inputs.runs-on }}
    name: "./gradlew ${{ inputs.gradle-task}} @ ${{ inputs.runs-on }}"
    timeout-minutes: 60
    steps:

      ### Install requirements ###

      - name: Install Linux dependencies
        id: setup-linux
        if: runner.os == 'Linux'
        run: >-
          sudo apt-get update 
          && sudo apt-get install librocksdb-dev libgflags-dev libsnappy-dev libbz2-dev liblz4-dev libzstd-dev
          && dpkg -L librocksdb-dev

      - name: Install macOS dependencies
        id: setup-macos
        if: runner.os == 'macOS'
        run: >-
          brew install rocksdb gflags snappy bzip2 lz4 zstd
          && brew --prefix rocksdb

      - uses: msys2/setup-msys2@v2
        if: runner.os == 'Windows'
        with:
          # msystem: MINGW64
          location: C:/msys2
          update: true
          # https://packages.msys2.org/package/mingw-w64-x86_64-rocksdb?repo=mingw64
          install: >
            mingw-w64-x86_64-rocksdb
            mingw-w64-x86_64-zstd
            mingw-w64-x86_64-zlib
            mingw-w64-x86_64-snappy
            mingw-w64-x86_64-lz4
            mingw-w64-x86_64-bzip2

      - if: runner.os == 'Windows'
        shell: msys2 {0}
        run:
          cygpath -m /
          && pacman -Ql mingw-w64-x86_64-rocksdb
          && pacman -Ql mingw-w64-x86_64-zstd
          && pacman -Ql mingw-w64-x86_64-zlib
          && pacman -Ql mingw-w64-x86_64-snappy
          && pacman -Ql mingw-w64-x86_64-lz4
          && pacman -Ql mingw-w64-x86_64-bzip2

      - if: runner.os == 'Windows'
        run: >-
          ls C:/
          && ls C:/msys2/msys64/
          && tree C:/msys2/msys64/ /F
          && tree C:/msys2/msys64/mingw64/ /F
          && echo $MSYS2_ROOT

      ### Gradle task ###

      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - id: cache-kotlin-konan
        uses: actions/cache@v3
        with:
          path: ~/.konan/**
          key: kotlin-konan-${{ runner.os }}

      - uses: gradle/gradle-build-action@v2
        with:
          gradle-home-cache-cleanup: true
          arguments: ${{ inputs.gradle-task }}

      - name: Upload build reports
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: build-report-${{ runner.os }}${{ github.action }}
          path: "**/build/reports/"
          if-no-files-found: ignore
