name: Gradle Task
run-name: "Gradle Task ${{ inputs.gradle-task }} @ ${{ inputs.runs-on }}"

# Reusable Workflow for running a Gradle task

on:
  workflow_dispatch:

  workflow_call:
    inputs:
      gradle-task:
        description: "The Gradle task to run, including any flags"
        required: true
        type: string
      runs-on:
        description: "OSes to run the task on"
        required: true
        type: string


concurrency:
  # note: the Workflow inputs are also included in the concurrency group
  group: "${{ github.workflow }} ${{ join(inputs.*) }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true


permissions:
  contents: read


jobs:

  run-task:
    runs-on: ${{ inputs.runs-on }}
    name: "./gradlew ${{ inputs.gradle-task}} @ ${{ inputs.runs-on }}"
    timeout-minutes: 60
    steps:

      ### Install requirements ###

      - name: Install Linux dependencies
        id: setup-linux
        if: runner.os == 'Linux'
        run: >-
          sudo apt-get update 
          && sudo apt-get install librocksdb-dev libgflags-dev libsnappy-dev libbz2-dev liblz4-dev libzstd-dev
          && dpkg -L librocksdb-dev

      - name: Install macOS dependencies
        id: setup-macos
        if: runner.os == 'macOS'
        run: >-
          brew install rocksdb gflags snappy bzip2 lz4 zstd
          && brew --prefix rocksdb

      - uses: actions/cache@v3
        id: cache-windows
        if: runner.os == 'Windows'
        with:
          path: |
            C:/msys64/mingw64
          key: static-libs-${{ runner.os }}
      #            ~/AppData/Local/vcpkg
      #            C:/vcpkg/downloads
      #            C:/vcpkg/installed
      #            C:/vcpkg/packages
      #            C:/vcpkg/buildtrees

      #      - name: Install Windows dependencies
      #        id: setup-windows
      #        if: runner.os == 'Windows'
      #        # https://vcpkg.io/en/docs/users/buildsystems/manual-integration.html
      ##          vcpkg install rocksdb gflags snappy bzip2 lz4 zstd --triplet x64-windows
      #        run: >-
      #          vcpkg install rocksdb --triplet x64-windows-static
      #          && echo "C:\vcpkg\installed\x64-windows-static\lib" >> $GITHUB_PATH
      #          && echo "C:\vcpkg\packages\rocksdb_x64-windows-static\lib" >> $GITHUB_PATH
      #          && ls C:\vcpkg\
      #          && ls C:\vcpkg\installed\x64-windows-static\lib\
      #          && tree C:\vcpkg\ /F
      ##          && ls C:\vcpkg\packages\rocksdb_x64-windows\lib

      - uses: msys2/setup-msys2@v2
        if: runner.os == 'Windows'
        with:
          msystem: MINGW64
          update: true
          install: mingw-w64-x86_64-rocksdb
      # https://packages.msys2.org/package/mingw-w64-x86_64-rocksdb?repo=mingw64

      - if: runner.os == 'Windows'
        shell: msys2 {0}
        run:
          pacman -Ql mingw-w64-x86_64-rocksdb
#          && pacman -Fl mingw-w64-x86_64-rocksdb

      - if: runner.os == 'Windows'
        run: tree C:/mingw64/ /F

      ### Gradle task ###

      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - id: cache-kotlin-konan
        uses: actions/cache@v3
        with:
          path: ~/.konan
          key: kotlin-konan-${{ runner.os }}

      - uses: gradle/gradle-build-action@v2
        with:
          gradle-home-cache-cleanup: true
          arguments: ${{ inputs.gradle-task }}

      - name: Upload build reports
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: build-report-${{ runner.os }}${{ github.action }}
          path: "**/build/reports/"
          if-no-files-found: ignore
