name: Tests

on:
  pull_request:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - main

concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true


permissions:
  contents: read


jobs:

  gradle-check:
    strategy:
      matrix:
        include:
          - os: macos-latest
            task: macosX64Test
          - os: ubuntu-latest
            task: linuxX64Test
          # currently unable to figure out what options Windows needs, so it's disabled
          # https://github.com/aSemy/kotlin-on-the-rocksdb/issues/2
          #- os: windows-latest
          #  task: mingwX64Test
      fail-fast: false
    uses: ./.github/workflows/gradle_task.yml
    with:
      runs-on: ${{ matrix.os }}
      gradle-task: >-
        ${{ matrix.task }} --stacktrace --info
